services:
  - type: web
    name: sinhhuynh:latest
    runtime: image
    image:
      url: docker.io/0703134283/cursus3:latest
    plan: free
    region: oregon
    env:
      MAIN_SERVICE_URL: http://192.168.1.100:8080
      AUTH_SERVICE_URL: http://192.168.1.101:8081
version: "1"
