version: "1"
services:
  - type: web
    name: sinhhuynh:latest
    runtime: image
    image:
      url: docker.io/0703134283/cursus3:latest
    plan: free
    region: oregon
    envVars:
      - key: PORT1
        value: "8080"
      - key: PORT2
        value: "8081"
    environment:
      - key: ADDITIONAL_HEADERS
        value: |
          [
            { "key": "Access-Control-Allow-Origin", "value": "*" },
            { "key": "Access-Control-Allow-Methods", "value": "GET, POST, PUT, DELETE, OPTIONS" },
            { "key": "Access-Control-Allow-Headers", "value": "Origin, X-Requested-With, Content-Type, Accept" }
          ]
